// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijzzaosfxxaxcioyixcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqenphb3NmeHhheGNpb3lpeGN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODI2MTEsImV4cCI6MjA1Nzg1ODYxMX0.bVpmqfAcpcN88U1h3OY7Nm_GKt73y6GzCNYQjO9DJDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);